### ISSUE TITLE
Test the A* search algorithm using the Map problem

### ISSUE THREAD

**Issue by fbarth** [fbarth/ai-espm#11]

**Comment by fbarth** [comment]
Before test the A* algorithm, you must define a good h() function for this problem.

**Comment by fbarth** [comment]
In order to test all scenarios, you must complete the file MapHeuristics.csv

**Comment by PG-Basso** [comment]
Are the current values for h on the file MapHeuristics.csv arbitrarily defined or is there a source from which i can calculate the h values for the missing scenarios?

**Comment by fbarth** [comment]
No. The current values are not arbitrarily. The heuristic from point A to point B is the straight-line distance between these two points.

**Comment by fbarth** [comment]
Ok! @PG-Basso have completed the MapHeuristics! Great! Now, anyone can test the A* algorithm against map problem.
